name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '16'
     - name: Install dependencies
       run: npm ci
     - name: Run tests using npm 7
       run: npm i npm@7 -g && npm t
     - name: Run tests using npm 6
       run: npm i npm@6 -g && npm t
